spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/watch_pro?serverTimezone=GMT%2b8
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource